In [1]:
import pandas as pd
import numpy as np
import visualz.datastats
import seaborn as sns
import matplotlib.pyplot as plt

%matplotlib inline

ModuleNotFoundError: No module named 'visualz.datastats'

Data Description of variables

In [2]:
data_def = pd.read_csv('Xente_Variable_Definitions.csv')
data_def

             Column Name                                         Definition
0          TransactionId         Unique �transaction identifier on platform
1                BatchId  Unique number assigned to a batch of transacti...
2              AccountId  Unique number identifying the customer on plat...
3         SubscriptionId  Unique number identifying the customer subscri...
4             CustomerId              Unique identifier attached to Account
5           CurrencyCode                                   Country currency
6            CountryCode             Numerical geographical code of country
7             ProviderId                   Source provider of Item �bought.
8              ProductId                            Item name being bought.
9        ProductCategory  ProductIds are organized into these broader pr...
10             ChannelId  Identifies if customer used web,Android, IOS, ...
11                Amount  Value of the transaction. Positive for debits ...
12                 Value                       Absolute value of the amount
13  TransactionStartTime                             Transaction start time
14       PricingStrategy  Category of Xente's pricing structure for merc...
15           FraudResult         Fraud status of transaction 1 -yes or 0-No

In [2]:
#Read in data set
train_data = pd.read_csv('training.csv')
test_data = pd.read_csv('test.csv')
weather_data = pd.read_excel('WeatherNairobi2016.xls')
sample_submission = pd.read_csv('sample_submission_xente.csv')

In [ ]:
viz.

In [8]:
print('Shape of train data is', train_data.shape)
print('Shape of test data is', test_data.shape)
print('Shape of weather data is', weather_data.shape)

Shape of train data is (95662, 16)
Shape of test data is (45019, 15)
Shape of weather data is (1373, 29)

In [6]:
train_data.head()

         TransactionId         BatchId       AccountId     ...      TransactionStartTime PricingStrategy FraudResult
0  TransactionId_76871   BatchId_36123  AccountId_3957     ...      2018-11-15T02:18:49Z               2           0
1  TransactionId_73770   BatchId_15642  AccountId_4841     ...      2018-11-15T02:19:08Z               2           0
2  TransactionId_26203   BatchId_53941  AccountId_4229     ...      2018-11-15T02:44:21Z               2           0
3    TransactionId_380  BatchId_102363   AccountId_648     ...      2018-11-15T03:32:55Z               2           0
4  TransactionId_28195   BatchId_38780  AccountId_4841     ...      2018-11-15T03:34:21Z               2           0

[5 rows x 16 columns]

In [11]:
train_data.describe()

       CountryCode        Amount         Value  PricingStrategy   FraudResult
count      95662.0  9.566200e+04  9.566200e+04     95662.000000  95662.000000
mean         256.0  6.717846e+03  9.900584e+03         2.255974      0.002018
std            0.0  1.233068e+05  1.231221e+05         0.732924      0.044872
min          256.0 -1.000000e+06  2.000000e+00         0.000000      0.000000
25%          256.0 -5.000000e+01  2.750000e+02         2.000000      0.000000
50%          256.0  1.000000e+03  1.000000e+03         2.000000      0.000000
75%          256.0  2.800000e+03  5.000000e+03         2.000000      0.000000
max          256.0  9.880000e+06  9.880000e+06         4.000000      1.000000